apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- serviceaccount.yaml
- servicemonitor.yaml

images:
- name: fintrackacr.azurecr.io/fintrack/backend
  newTag: 7ef4c4e7a316542ec9d6a1265e04daf9a07ab92f
