apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- serviceaccount.yaml
- servicemonitor.yaml

images:
- name: fintrackacr.azurecr.io/fintrack/backend
  newTag: 8bbab6bf7db77365f97d5eef8eb87e0418683fab
