apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: fintrackacr.azurecr.io/fintrack/frontend
  newTag: 4f254761c81e2a37e97071aa30c585175eb528c1
