apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: application
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://fintrack-kv-32b5eb4b.vault.azure.net
      serviceAccountRef:
        name: external-secrets