apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: application
  annotations:
    azure.workload.identity/client-id: "b30dc573-9bc2-49b6-b682-e02d694978ee"
    azure.workload.identity/tenant-id: "84a27e7f-aba3-4a79-b888-2c4c75fabd39"
  labels:
    azure.workload.identity/use: "true"
