apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: application
  annotations:
    azure.workload.identity/client-id: "b30dc573-9bc2-49b6-b682-e02d694978ee"
  labels:
    azure.workload.identity/use: "true"
